# PyTorch Tensor

In [1]:
import torch

## Tensor Allocation

In [4]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt  

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

## NumPy Compatibility

In [8]:
import numpy as np

# DEFINE NUMPY ARRAY.
x = np.array([[1, 0],
              [0, 1]])
print(x, type(x))

[[1 0]
 [0 1]] <class 'numpy.ndarray'>


In [9]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 0],
        [0, 1]]) <class 'torch.Tensor'>


In [10]:
x = x.numpy()
print(x, type(x))

[[1 0]
 [0 1]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [11]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [12]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [13]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [15]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

In [16]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


### Get number of dimensions in the tensor.

In [18]:
print(x.dim())
print(len(x.size()))

3
3


### Get number of elements in certain dimension of the tensor.

In [19]:
print(x.size(1))
print(x.shape[1])

2
2


### Get number of elements in the lasst dimension.

In [20]:
print(x.size(-1))
print(x.shape[-1])

2
2
