# PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [2]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [3]:
y = x.expand(*[2, 3, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### Implement expand with cat.

In [4]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([1, 4, 8, 7, 9, 3, 5, 6, 0, 2])
torch.Size([10])


### argmax: Return index of maximum values

In [6]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[ 5,  4, 21],
         [ 8,  9, 22],
         [12,  0, 24]],

        [[13,  1, 26],
         [18, 10,  7],
         [16, 11, 17]],

        [[ 6, 25, 23],
         [ 3, 15, 19],
         [14, 20,  2]]])
torch.Size([3, 3, 3])


In [7]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[2, 2, 2],
        [2, 0, 2],
        [1, 2, 1]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [13]:
values, indices = torch.topk(x, k=1, dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [9]:
print(values. squeeze(-1))
print(indices.squeeze(-1))

tensor([[21, 22, 24],
        [26, 18, 17],
        [25, 19, 20]])
tensor([[2, 2, 2],
        [2, 0, 2],
        [1, 2, 1]])


In [10]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [16]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)
print(values)

tensor([[[21,  5,  4],
         [22,  9,  8],
         [24, 12,  0]],

        [[26, 13,  1],
         [18, 10,  7],
         [17, 16, 11]],

        [[25, 23,  6],
         [19, 15,  3],
         [20, 14,  2]]])


### Topk by using sort

In [17]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[ 5,  9, 12],
        [13, 10, 16],
        [23, 15, 14]])
tensor([[2, 2, 2],
        [2, 0, 2],
        [1, 2, 1]])


### masked_fill: fill the value if element of mask is True

In [18]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [19]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [21]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [22]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [25]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
