# Linear Layer

In [1]:
import torch

## Raw Linear Layer

In [3]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [4]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [5]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b

    return y

In [6]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])

print(x.size())

torch.Size([4, 3])


In [7]:
y = linear(x, W, b)

In [8]:
print(y.size())

torch.Size([4, 2])


## nn.Module

In [9]:
import torch.nn as nn

In [10]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    # You should override 'forward' method to implement detail.
    # The input arguments and outputs can be designed as you wish.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)

        return y

In [11]:
linear = MyLinear(3, 2)

y = linear(x)

In [12]:
print(y.size())

torch.Size([4, 2])


In [13]:
for p in linear.parameters():
    print(p)

You can see that there is no weight parameters to learn. <br>
Above way can forward(or calculate) values, but it cannot be trained.

### Correct way: nn.Parameter

In [16]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        super().__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)

        return y

In [20]:
linear = MyLinear(3, 2)

y = linear(x)

In [21]:
print(y.size())

torch.Size([4, 2])


In [23]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-2.3110e-19,  3.0899e-41],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]], requires_grad=True)
Parameter containing:
tensor([-1.9699e-19,  3.0899e-41], requires_grad=True)


### nn.Module can contain other nn.Module's child classes.

In [32]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = self.linear(x)
        # |y| = (batch_size, output_dim)

        return y

In [33]:
linear = MyLinear(3, 2)

y = linear(x)

In [34]:
print(y.size())

torch.Size([4, 2])


In [35]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.1768,  0.1391,  0.0604],
        [-0.3942, -0.0982, -0.5750]], requires_grad=True)
Parameter containing:
tensor([ 0.2720, -0.0873], requires_grad=True)
