# How to use GPU

In [2]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [3]:
x = torch.cuda.FloatTensor(2, 2)
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [8]:
x = torch.FloatTensor(2, 2)
x

tensor([[ 5.1645e-17,  4.5687e-41],
        [-1.3526e+19,  3.0665e-41]])

In [9]:
x.cuda()

tensor([[ 5.1645e-17,  4.5687e-41],
        [-1.3526e+19,  3.0665e-41]], device='cuda:0')

In [10]:
d = torch.device('cuda:0')

In [11]:
x.cuda(device=d)

tensor([[ 5.1645e-17,  4.5687e-41],
        [-1.3526e+19,  3.0665e-41]], device='cuda:0')

In [12]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [13]:
x.to(device=d)

tensor([[ 5.1645e-17,  4.5687e-41],
        [-1.3526e+19,  3.0665e-41]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [14]:
x = torch.cuda.FloatTensor(2, 2)

In [15]:
x = x.cpu()

In [17]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [18]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [19]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.2737, -0.6513],
        [-0.2073, -0.5270]], requires_grad=True)
Parameter containing:
tensor([0.3289, 0.0499], requires_grad=True)


In [20]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.2737, -0.6513],
        [-0.2073, -0.5270]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.3289, 0.0499], device='cuda:0', requires_grad=True)


In [21]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.2737, -0.6513],
        [-0.2073, -0.5270]], requires_grad=True)
Parameter containing:
tensor([0.3289, 0.0499], requires_grad=True)


In [22]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[ 0.2737, -0.6513],
        [-0.2073, -0.5270]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.3289, 0.0499], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [23]:
linear.device

AttributeError: 'Linear' object has no attribute 'device'

## Tricks

In [24]:
x = torch.cuda.FloatTensor(2, 2)

In [25]:
x.new(2, 2)

tensor([[2.3694e-38, 4.6293e+02],
        [1.4013e-45, 0.0000e+00]], device='cuda:0')

In [26]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [27]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [28]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')